"""Generate the Kaggle kernel notebook (`kernel.ipynb`) as a THIN bootstrap.

The notebook is intentionally tiny and (after one browser "Save & Run All") never
needs editing again: it installs deps, clones/pulls the repo, and `runpy`s the
orchestrator from the pulled repo. So all future logic — the package AND
`kaggle/run_experiment.py` — ships via `git push`; the kernel always runs latest.

Run:  python kaggle/make_kernel_notebook.py
"""
import json
import pathlib
import uuid

HERE = pathlib.Path(__file__).parent
REPO_URL = "https://github.com/pra-nav-04/safety-circuits.git"

BOOTSTRAP = f'''\
# safety-circuits — thin bootstrap (auto-generated by make_kernel_notebook.py).
# Installs deps, pulls latest repo, runs an orchestrator from it.
# Configure the run with SC_* env vars in a cell ABOVE this one, e.g.:
#   import os; os.environ["SC_MODELS"] = "gemma3-1b,qwen"   # subset / resume
#   os.environ["SC_ORCHESTRATOR"] = "run_edit_experiment.py"  # §9 editing suite
import os, pathlib, subprocess, sys

# HF token (gated models: gemma-3, llama-3.2) from Kaggle secrets, if configured.
try:
    from kaggle_secrets import UserSecretsClient
    os.environ["HF_TOKEN"] = UserSecretsClient().get_secret("HF_TOKEN")
    print("HF_TOKEN loaded from Kaggle secrets.")
except Exception:
    pass

subprocess.run([sys.executable, "-m", "pip", "install", "-q",
    "transformer-lens>=2.0.0", "transformers>=4.40", "datasets>=2.18",
    "accelerate>=0.27", "einops>=0.7", "seaborn", "tqdm", "pyyaml", "jaxtyping",
    "peft>=0.10",   # §9 editing extension (LoRA); harmless for the main study
], check=True)

# Kaggle's image periodically downgrades torch while keeping torchaudio/torchvision
# pinned to the old torch — and recent transformers EAGERLY imports torchaudio when
# `import transformer_lens` runs, crashing with an undefined-symbol error before any
# of our code executes. We use neither extension, so drop them to skip that import.
subprocess.run([sys.executable, "-m", "pip", "uninstall", "-y", "torchaudio", "torchvision"],
               check=False)

repo = pathlib.Path("/tmp/safety-circuits")   # /tmp keeps it out of the output bundle
if repo.exists():
    subprocess.run(["git", "-C", str(repo), "pull"], check=True)
else:
    subprocess.run(["git", "clone", "--depth=1", "{REPO_URL}", str(repo)], check=True)

sys.path.insert(0, str(repo / "src"))

# Drop any stale copies cached from a previous run in THIS kernel so the freshly pulled
# code (and the torchaudio/torchvision import shim) actually loads — without needing a
# manual "Restart session". Keep torch itself; only purge what we reload.
for _m in [m for m in list(sys.modules)
           if m.split(".")[0] in ("safety_circuits", "transformer_lens", "transformers",
                                   "torchaudio", "torchvision")]:
    del sys.modules[_m]

# Which orchestrator to run: the main multi-model study (default) or the §9 editing
# suite. Set os.environ["SC_ORCHESTRATOR"] in a cell above to switch — the notebook
# itself never needs editing.
orchestrator = os.environ.get("SC_ORCHESTRATOR", "run_experiment.py")
import runpy
_ = runpy.run_path(str(repo / "kaggle" / orchestrator), run_name="__main__")  # _ = … hides the namespace dump
'''

lines = BOOTSTRAP.splitlines(keepends=True)

nb = {
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "pygments_lexer": "ipython3", "version": "3.12.0"},
    },
    "nbformat": 4,
    "nbformat_minor": 4,
    "cells": [
        {
            "cell_type": "code",
            "execution_count": None,
            "id": uuid.uuid4().hex[:8],
            "metadata": {},
            "outputs": [],
            "source": lines,
        }
    ],
}

out = HERE / "kernel.ipynb"
out.write_text(json.dumps(nb))
assert json.loads(out.read_text())["cells"][0]["source"] == lines  # sanity
print(f"Written {out}  ({out.stat().st_size} bytes, {len(lines)} bootstrap lines)")
